oar_debian_config_frontend:
 - configure_apache2:
   - exec_chroot: a2enmod ident
   - exec_chroot: a2enmod headers
   - exec_chroot: a2enmod rewrite

 - configure_basic_auth_api-priv:
   - exec_chroot: ln -s /etc/oar/apache2/oar-restful-api-priv.conf /etc/apache2/conf.d/oar-restful-api-priv.conf

