oar_centos_config_server:
 - configure_mysql:
   - exec_chroot: service mysqld start
   - exec_chroot: chkconfig mysqld on
   - exec_on_clean: chroot $$chroot bash -c "service mysqld stop || true"

 - configure_initd:
   - exec_chroot: cp $$oar_prefix_install/share/doc/oar-server/examples/init.d/oar-server /etc/rc.d/init.d/
   - exec_chroot: cp $$oar_prefix_install/share/doc/oar-server/examples/default/oar-server /etc/sysconfig/
   - exec_chroot: chkconfig --add oar-server
   - exec_chroot: chkconfig oar-server on
