oar_centos_config_frontend:
 - configure_apache2:
   - write_file:
     - /etc/httpd/conf.d/identd.conf
     - |
       LoadModule ident_module modules/mod_ident.so
   - exec_chroot: chkconfig httpd on

 - configure_basic_auth_api-priv:
   - exec_chroot: ln -sf /etc/oar/apache2/oar-restful-api-priv.conf /etc/httpd/conf.d/oar-restful-api-priv.conf

